version: '3'

services:
  mongo:
    container_name: torahbot-mongo
    build:
      context: mongo/
    ports:
      - "27017:27017"
  redis:
    container_name: torahbot-redis
    image: redis:7.0.5
